image:
  path: C://PjImg/

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/furniture
    username: root
    password: 2714

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

